/**
 * [INPUT]: 依赖 @/lib/locale 的 Locale 类型，承载 app shell、login、workspace、record 的本地化文案字典。
 * [OUTPUT]: 对外提供 copy 字典、getCopy 与按 locale 取值的辅助类型。
 * [POS]: lib 的文案真相源，集中管理页面可见文本，禁止组件继续内联双语字符串。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import type { Locale } from '@/lib/locale'

type LocaleText = Record<Locale, string>

function text(zh: string, en: string): LocaleText {
  return { zh, en }
}

export const copy = {
  app: {
    boot: {
      status: text('会话恢复', 'Session Restore'),
      title: text('正在恢复访问状态', 'Restoring session access'),
    },
    userLabel: {
      anonymous: text('匿名会话', 'Anonymous Session'),
      authenticated: text('认证会话', 'Authenticated Session'),
    },
  },
  localeToggle: {
    zh: text('中文', 'Chinese'),
    en: text('英文', 'English'),
  },
  themeToggle: {
    dark: text('深色', 'Dark'),
    light: text('浅色', 'Light'),
  },
  shell: {
    brand: {
      darkHeader: text('档案系统 V1', 'Archive System V1'),
      darkTitle: text('一页萤屿', 'Firefly Isle'),
      darkSubtitle: text('临床 AI 控制台', 'Clinical AI Console'),
      lightTitle: text('一页萤屿', 'Firefly Isle'),
      lightSubtitle: text('临床 AI 工作台', 'Clinical AI Workspace'),
    },
    topbar: {
      volume: text('第 01 卷 · 第 52 期', 'VOL. 01 — NO. 52'),
      workspace: text('临床 AI 工作台', 'Clinical AI Workspace'),
      established: text('创立于 2024', 'EST. 2024'),
    },
    nav: {
      extract: text('提取', 'Extract'),
      record: text('病历', 'Record'),
      analytics: text('统计', 'Analytics'),
      newExtraction: text('新建提取', 'New Extraction'),
      themeToggle: text('切换主题', 'Toggle Theme'),
      signOut: text('退出登录', 'Sign Out'),
      signingOut: text('会话结束中', 'Ending Session'),
      userProfile: text('用户资料', 'User Profile'),
      pendingAccess: text('访问待定', 'Access Pending'),
      avatarAlt: text('用户头像', 'User Avatar'),
    },
  },
  login: {
    footer: {
      copyrightDark: text('© 2024 一页萤屿档案', '© 2024 Firefly Isle Archive'),
      secureLink: text('安全链路已激活', 'Secure Link Active'),
      copyrightLight: text('© 2024 一页萤屿档案系统', '© 2024 Firefly Isle Archive System'),
      privacyPolicy: text('隐私政策', 'Privacy Policy'),
      systemStatus: text('系统状态', 'System Status'),
      supportCluster: text('支持集群', 'Support Cluster'),
      fullPrivacy: text('查看完整隐私条款', 'Read full privacy policy'),
    },
    hero: {
      badge: text('临床 AI 智能引擎', 'Clinical AI Intelligence'),
      titleLine1: text('把复杂治疗史', 'Turn complex treatment history'),
      titleLine2: text('整理成', 'into'),
      titleAccent: text('一页纸', 'one page'),
      subtitle: text('临床精密性的本质在于对复杂信息的降维与提取。', 'Clinical precision begins with compressing and extracting complex information.'),
      ready: text('系统已就绪，可开始分析', 'System ready for analysis'),
    },
    auth: {
      heading: text('身份访问控制台', 'Access Console'),
      authentication: text('身份验证', 'Authentication'),
      login: text('登录', 'Login'),
      signup: text('注册', 'Sign Up'),
      submitLogin: text('验证并进入控制台', 'Verify and enter console'),
      submitSignup: text('创建账户并发送验证邮件', 'Create account and send verification email'),
      submitLoginLight: text('验证并进入系统', 'Verify and enter system'),
      dividerLogin: text('或使用邮箱凭证', 'Or use email credentials'),
      dividerSignup: text('邮箱建档入口', 'Create account with email'),
      thirdPartyAuth: text('第三方鉴权', 'Third-party authentication'),
      wechat: text('微信', 'WeChat Sign In'),
      google: text('谷歌', 'Google Sign In'),
      emailLabel: text('注册邮箱', 'Registered Email'),
      emailLabelLight: text('电子邮箱', 'Electronic Mail'),
      emailPlaceholder: text('输入临床邮箱', 'Enter clinical email'),
      emailPlaceholderLight: text('输入邮箱地址', 'Enter email address'),
      passwordLabel: text('加密密钥', 'Encryption Key'),
      passwordLabelLight: text('密码', 'Password'),
      passwordPlaceholder: text('输入 256 位加密密钥', 'Enter 256-bit encryption key'),
      passwordPlaceholderLight: text('••••••••', '••••••••'),
      anonymous: text('无需登录，直接使用匿名会话', 'Use anonymous session without signing in'),
      footerPrivacyPrefix: text('继续即表示你同意', 'By continuing, you agree to the'),
      footerPrivacyLink: text('隐私政策', 'Privacy Policy'),
      secureGateway: text('身份访问管理', 'Identity Access Management'),
      secureGatewayDetail: text('安全网关', 'Secure Gateway'),
    },
    lightHero: {
      titleLine1: text('把复杂治疗史', 'Turn complex treatment history'),
      titleLine2: text('整理成一页纸', 'into one page'),
      body: text('在数字化医疗的洪流中，信息的碎片化成为了精准诊疗的阻碍。一页萤屿利用先进的语义提取引擎，将跨度数年的电子病历、检验报告及主观叙述，浓缩为具备高度逻辑性的临床全景。我们不只是在整理数据，更是在重构生命叙事。', 'In digital medicine, fragmented information blocks precise care. Firefly Isle uses semantic extraction to condense years of records, lab reports, and narratives into a coherent clinical panorama. We do not just organize data; we reconstruct the patient story.'),
      precisionTag: text('精度 // 01', 'Precision // 01'),
      precisionTitle: text('结构化重塑', 'Structured Remodeling'),
      precisionBody: text('自动识别 140 余种临床实体，将非结构化文本转化为标准医学图谱。', 'Automatically identifies more than 140 clinical entities and converts unstructured text into a standardized medical graph.'),
      intelligenceTag: text('智能 // 02', 'Intelligence // 02'),
      intelligenceTitle: text('时间轴推理', 'Timeline Reasoning'),
      intelligenceBody: text('跨时空对比关键指标变化，自动勾勒病情进展与治疗反应曲线。', 'Compares key indicators across time and automatically maps disease progression and treatment response.'),
      certification: text('临床数据加密标准 ISO-27001 认证', 'Clinical Data Encryption Standard ISO-27001 Certified'),
    },
    stats: {
      uptime: text('运行时间', 'Uptime'),
      usersOnline: text('在线用户', 'Users Online'),
    },
  },
  workspace: {
    composer: {
      inputLabel: text('病史输入', 'Patient History Input'),
      inputPlaceholder: text('请描述患者的病情及治疗历程...', 'Describe the patient condition and treatment history...'),
      importRecordFile: text('导入病历文件', 'Import record file'),
      voiceInput: text('语音输入', 'Voice input'),
      extract: text('开始结构化提取', 'Start Structured Extraction'),
      extracting: text('提取中…', 'Extracting…'),
      retryInitial: text('重试提取', 'Retry Extraction'),
      retryFollowUp: text('重试这轮补充', 'Retry Follow-up'),
      exportPdf: text('导出 PDF', 'Export PDF'),
      exportPdfLoading: text('导出 PDF 中…', 'Exporting PDF…'),
      exportPng: text('导出 PNG', 'Export PNG'),
      exportPngLoading: text('导出 PNG 中…', 'Exporting PNG…'),
      saving: text('保存中…', 'Saving…'),
      processing: text('处理中…', 'Processing…'),
      followUps: text('最多 3 轮', 'Up to 3 rounds'),
      model: text('模型', 'Model'),
      missing: text('缺失字段', 'Missing'),
      instructionalTitle: text('使用说明', 'Instructions'),
      instructionalBody: text('先输入完整病史，再根据追问一次性补充缺失的临床关键字段。当前仅对肿瘤类型、分期与治疗方案触发追问。', 'Start with a complete patient history, then answer follow-up prompts in one pass to fill critical clinical gaps. Follow-ups currently target tumor type, stage, and regimen only.'),
      currentParameters: text('当前参数', 'Current Parameters'),
      textInput: text('文字输入', 'Text Input'),
      ready: text('准备分析', 'Ready to Analyze'),
      analyzing: text('分析中', 'Analyzing'),
      voice: text('语音录入', 'Voice Input'),
      holdToRecord: text('按住录音', 'Hold to Record'),
      sessionId: text('会话编号：AI-2949-01', 'Session ID: AI-2949-01'),
      location: text('地点：上海诊室', 'Location: Shanghai Clinic'),
      date: text('日期：2024.05.20', 'Date: 2024.05.20'),
      extractor: text('提取器', 'Extractor'),
      gemini: text('Gemini', 'Gemini'),
    },
    followUp: {
      title: text('补充追问', 'Follow-up'),
      placeholder: text('一次性补充缺失信息...', 'Fill in the missing information in one pass...'),
      submit: text('提交补充', 'Submit Follow-up'),
    },
    report: {
      title: text('临床结构化报告', 'Structured Clinical Report'),
      generatedBy: text('由一页萤屿 AI 档案系统生成', 'Generated by Firefly Isle AI Archive'),
      reportId: text('报告编号：实时草稿', 'Report ID: Live Draft'),
      missingPrefix: text('缺失字段：', 'Missing Fields: '),
      disclaimer: text('声明：本报告由人工智能辅助系统自动提取，仅供医疗专业人士参考。最终诊断需结合原始影像及病理报告。', 'Disclaimer: This report is automatically extracted by an AI-assisted system for medical professionals only. Final diagnosis must be confirmed against original imaging and pathology reports.'),
      verifyQr: text('扫码验证报告', 'Scan to verify report'),
      clinicalNotes: text('临床备注', 'Clinical Notes'),
      missingFields: text('仍待补充：', 'Still missing: '),
      completed: text('关键临床字段已补齐，可进入下一阶段渲染。', 'Critical clinical fields are complete and ready for the next stage.'),
      verifiedBy: text('AI 助手已校验', 'Verified by AI Agent'),
      followUpsUsed: text('已使用追问轮次：', 'Follow-ups used: '),
      footerBrand: text('墨迹与档案', 'Ink & Archive'),
      footerProtocol: text('协议：临床 ALPHA-01 // 无未匹配数据', 'Protocol: Clinical ALPHA-01 // No unmatched data'),
      engineLabel: text('临床智能引擎', 'Clinical Intelligence Engine'),
    },
    errors: {
      exportPdf: text('PDF 导出失败，请稍后重试。', 'PDF export failed. Please try again later.'),
      exportPng: text('PNG 导出失败，请稍后重试。', 'PNG export failed. Please try again later.'),
      loadLatest: text('无法恢复最近一次患者记录，请刷新后重试。', 'Could not restore the latest patient record. Please refresh and try again.'),
      missingInput: text('请先输入病情描述，再开始提取。', 'Enter the patient history before starting extraction.'),
      savePatient: text('患者记录保存失败，请稍后重试。', 'Saving the patient record failed. Please try again later.'),
      saveTreatmentLine: text('治疗线保存失败，请稍后重试。', 'Saving the treatment line failed. Please try again later.'),
    },
  },
  timeline: {
    tableTitle: text('病历预览', 'Record Preview'),
    basicInfoTitle: text('基本信息', 'Basic Information'),
    basicInfoSubtitle: text('基础信息区块', 'Basic Info Block'),
    criticalFields: text('关键字段：肿瘤类型 / 分期 / 治疗方案', 'Critical Fields: Tumor Type / Stage / Regimen'),
    gender: text('性别', 'Gender'),
    age: text('年龄', 'Age'),
    height: text('身高', 'Height'),
    weight: text('体重', 'Weight'),
    tumorType: text('肿瘤类型', 'Tumor Type'),
    diagnosisDate: text('诊断日期', 'Diagnosis Date'),
    stage: text('分期', 'Stage'),
    initialOnsetTitle: text('初发区块', 'Initial Onset'),
    regimen: text('治疗方案', 'Regimen'),
    triggerDate: text('初发时间', 'Trigger Date'),
    immunohistochemistry: text('免疫组化', 'Immunohistochemistry'),
    genetic: text('基因检测', 'Genetic Analysis'),
    treatmentLine: text('治疗线', 'Line'),
    startDate: text('开始时间', 'Start Date'),
    endDate: text('结束时间', 'End Date'),
    biopsy: text('活检', 'Biopsy'),
    emptyTitle: text('尚未生成初发区块或治疗线。', 'No initial onset block or treatment lines yet.'),
    emptyBody: text('提交患者描述后，这里会按患者类型自动切换布局，并对关键缺失字段做高亮提示。', 'After you submit the patient narrative, this area will switch layouts by archetype and highlight critical missing fields.'),
    emptyStateKey: text('时间线状态', 'Timeline State'),
    tableKey: text('时间线表格', 'Timeline Table'),
    archetypeKey: text('患者类型', 'Archetype'),
    archetypeLabels: {
      deNovoAdvanced: text('初诊晚期', 'De Novo Advanced'),
      nonAdvanced: text('非晚期', 'Non-Advanced'),
      relapsedAdvanced: text('复发晚期', 'Relapsed Advanced'),
    },
    initialOnsetSubtitle: text('初发', 'Initial Onset'),
    treatmentLineSubtitle: text('治疗线', 'Treatment Line'),
  },
  workspaceShell: {
    footerProtocol: text('协议：临床 ALPHA-01 // 无未匹配数据', 'Protocol: Clinical ALPHA-01 // No unmatched data'),
  },
  recordPage: {
    dark: {
      initialOnsetTitle: text('初发诊断', 'Initial Onset'),
      initialOnsetDiagnosis: text('非小细胞肺癌', 'Non-Small Cell Lung Cancer'),
      initialOnsetSummary: text('患者于 2023 年 4 月因持续性咳嗽及胸痛就诊。CT 检查显示左上肺占位性病变（3.2cm x 2.8cm），伴有纵隔淋巴结肿大。活检病理确认为肺腺癌。', 'The patient presented in April 2023 with persistent cough and chest pain. CT showed a left upper lung mass (3.2cm x 2.8cm) with mediastinal lymphadenopathy. Biopsy pathology confirmed lung adenocarcinoma.'),
      immunohistochemistry: text('免疫组化', 'Immunohistochemistry'),
      geneticAnalysis: text('基因检测', 'Genetic Analysis'),
      line1Title: text('一线治疗', 'Line 01'),
      line1Badge: text('阶段完成', 'Phase Completed'),
      line1Therapy: text('奥希替尼靶向治疗', 'Osimertinib Targeted Therapy'),
      line1Summary: text('患者开始接受第三代 EGFR-TKI 治疗。初始反应良好，肿瘤体积缩小约 40%。治疗 9 个月后，复查显示左肺病灶增大，并出现微小脑转移灶，判定为疾病进展。', 'The patient started third-generation EGFR-TKI therapy with a strong initial response, shrinking the tumor by about 40%. After 9 months, follow-up imaging showed enlargement of the left lung lesion and small brain metastases, indicating disease progression.'),
      resistanceAnalysis: text('耐药分析', 'Resistance Analysis'),
      resistanceBody: text('检测到 EGFR T790M 突变消失，伴随 MET 基因扩增（FISH 阳性）。', 'EGFR T790M loss was detected together with MET amplification (FISH positive).'),
      line2Title: text('二线治疗', 'Line 02'),
      line2Badge: text('进行中', 'In Progress'),
      line2Therapy: text('培美曲塞 + 卡铂 + 赛沃替尼', 'Pemetrexed + Carboplatin + Savolitinib'),
      line2Summary: text('针对 MET 扩增，调整方案为化疗联合 MET 抑制剂治疗。目前已完成 4 个周期。患者自述呼吸困难症状缓解，脑部病灶稳定。', 'For MET amplification, the regimen was adjusted to chemotherapy plus a MET inhibitor. Four cycles have been completed, with improved dyspnea and stable brain lesions.'),
      aiConfidenceLog: text('AI 置信记录', 'AI Confidence Log'),
      matchScore: text('方案匹配度：94.2%', 'Regimen Match: 94.2%'),
      stabilityIndex: text('稳定性指标', 'Stability Index'),
      stabilityValue: text('稳定预期', 'Stable Predicted'),
      prognosisValue: text('预后偏乐观', 'Prognosis Optimistic'),
      verificationStamp: text('核验标记', 'Verification Stamp'),
      verificationBody: text('此档案由萤屿临床 AI 自动提取并结构化。所有数据点均经过病理报告与影像诊断交叉验证。', 'This archive is automatically extracted and structured by Firefly Isle Clinical AI. Every data point is cross-checked against pathology and imaging evidence.'),
      authorizedSystem: text('授权系统', 'Authorized System'),
      scrollAudit: text('滚动审阅', 'Scroll to Audit'),
    },
    light: {
      archive: text('病历档案', 'The Archive'),
      recordId: text('档案编号', 'Record ID'),
      lastUpdated: text('最后更新：2023.10.15', 'Last Updated: 2023.10.15'),
      reportRail: text('时间顺序报告', 'Chronological Report'),
      initialOnsetTitle: text('初发诊断', 'Initial Onset'),
      initialOnsetBody: text('患者于2021年10月因持续性干咳就诊。胸部CT显示左肺下叶占位，大小约 3.2 x 2.8 cm，伴纵隔淋巴结肿大。纤维支气管镜活检确诊为肺腺癌。病理分期定为 T2aN2M0 (IIIA期)。', 'The patient presented in October 2021 with persistent dry cough. Chest CT showed a left lower lobe mass about 3.2 x 2.8 cm with mediastinal lymphadenopathy. Bronchoscopic biopsy confirmed lung adenocarcinoma, staged as T2aN2M0 (stage IIIA).'),
      initialOnsetQuote: text('“诊断过程伴随显著体重减轻，患者自述伴有阵发性胸痛。”', '"The diagnostic course included marked weight loss, and the patient reported intermittent chest pain."'),
      ihcMarkers: text('IHC 标记', 'IHC Markers'),
      line1Title: text('一线治疗', 'Line 01'),
      geneticData: text('基因数据', 'Genetic Data'),
      geneticSubtitle: text('检测到 19 外显子缺失', 'Exon 19 Deletion Detected'),
      protocol: text('治疗方案', 'Protocol'),
      protocolSubtitle: text('80mg 每日一次，口服', '80mg qd, Oral'),
      line1Body: text('基因检测提示EGFR 19号外显子缺失。患者开始接受第三代TKI奥希替尼治疗。初期疗效评价为PR（部分缓解），肿瘤缩小40%以上。治疗期间耐受良好，主要副作用为I级皮疹及偶发腹泻，均在可控范围内。', 'Genetic testing identified an EGFR exon 19 deletion. The patient started third-generation TKI therapy with osimertinib and achieved a partial response with more than 40% tumor shrinkage. Tolerance remained good, with only grade 1 rash and occasional diarrhea.'),
      line2Title: text('二线治疗', 'Line 02'),
      resistanceDetected: text('已检测到耐药', 'Resistance Detected'),
      line2Body: text('2023年7月随访发现疾病进展（PD），左肺原发灶增大，并出现多发骨转移（肋骨、椎体）。进行二次活检及液体活检，未发现T790M突变，提示复杂的耐药机制，可能涉及c-MET扩增。', 'Follow-up in July 2023 showed progression with enlargement of the primary left lung lesion and multiple bone metastases in the ribs and vertebrae. Repeat tissue and liquid biopsy found no T790M mutation, suggesting a complex resistance mechanism that may involve c-MET amplification.'),
      newPlan: text('新方案拟定', 'New Plan'),
      newPlanBody: text('联合抗血管生成治疗以应对骨转移风险。', 'Anti-angiogenic combination therapy was selected to address bone metastasis risk.'),
      riskWarning: text('风险提示', 'Risk Warning'),
      verification: text('核验说明', 'Verification'),
      verificationBody: text('此报告由一页萤屿临床 AI 系统根据原始病历扫描件及病理报告自动生成。结构化数据已通过三级审核。所有临床决策须由主治医师最终确认。', 'This report is automatically generated by Firefly Isle Clinical AI from original scans and pathology reports. Structured data has passed three review stages. All clinical decisions must be confirmed by the attending physician.'),
      exportPdf: text('导出 PDF', 'Export PDF'),
      editData: text('修正数据', 'Edit Data'),
      copyright: text('© 2024 临床智能档案。保留所有权利。', '© 2024 Clinical Intelligence Archive. All rights reserved.'),
    },
  },
  record: {
    dark: {
      archiveNode: text('档案节点：', 'Archive Node: '),
      title: text('临床病史档案', 'Clinical Record Archive'),
      initialOnset: text('初发诊断', 'Initial Onset'),
      line1: text('一线治疗', 'Line 01'),
      line2: text('二线治疗', 'Line 02'),
      completed: text('阶段完成', 'Phase Completed'),
      inProgress: text('进行中', 'In Progress'),
      resistanceAnalysis: text('耐药分析', 'Resistance Analysis'),
      confidenceLog: text('AI 置信记录', 'AI Confidence Log'),
      stabilityIndex: text('稳定性指标', 'Stability Index'),
      verificationStamp: text('核验标记：', 'Verification Stamp:'),
      verificationBody: text('此档案由萤屿临床 AI 自动提取并结构化。所有数据点均经过病理报告与影像诊断交叉验证。', 'This archive is automatically extracted and structured by Firefly Isle Clinical AI. Every data point is cross-checked against pathology and imaging evidence.'),
      authorizedSystem: text('授权系统', 'Authorized System'),
      scrollAudit: text('滚动审阅', 'Scroll to Audit'),
      subjectId: text('受试者编号', 'Subject ID'),
      creationDate: text('创建日期', 'Creation Date'),
      securityProtocol: text('安全协议', 'Security Protocol'),
      dataNode: text('数据节点', 'Data Node'),
      age: text('年龄', 'Age'),
      bloodType: text('血型', 'Blood Type'),
      height: text('身高', 'Height'),
      weight: text('体重', 'Weight'),
      ihc: text('免疫组化', 'Immunohistochemistry'),
      genetic: text('基因检测', 'Genetic Analysis'),
    },
    light: {
      archiveNode: text('档案节点', 'Archive Node'),
      archiveTitle: text('临床病史档案', 'Clinical Record Archive'),
      patientName: text('陈先生', 'Mr. Chen'),
      patientSummary: text('男性 / 64 岁', 'Male / 64 Years'),
      archive: text('病历档案', 'The Archive'),
      age: text('年龄', 'Age'),
      bloodType: text('血型', 'Blood Type'),
      height: text('身高', 'Height'),
      weight: text('体重', 'Weight'),
      recordId: text('档案编号：', 'Record ID: '),
      lastUpdated: text('最后更新：2023.10.15', 'Last Updated: 2023.10.15'),
      reportRail: text('时间顺序报告', 'Chronological Report'),
      initialOnset: text('初发诊断', 'Initial Onset'),
      line1: text('一线治疗', 'Line 01'),
      line2: text('二线治疗', 'Line 02'),
      ihcMarkers: text('IHC 标记', 'IHC Markers'),
      geneticData: text('基因数据', 'Genetic Data'),
      protocol: text('治疗方案', 'Protocol'),
      resistanceDetected: text('已检测到耐药', 'Resistance Detected'),
      newPlan: text('新方案拟定', 'New Plan'),
      riskWarning: text('风险提示', 'Risk Warning'),
      verification: text('核验说明', 'Verification'),
      verificationBody: text('此报告由一页萤屿临床 AI 系统根据原始病历扫描件及病理报告自动生成。结构化数据已通过三级审核。所有临床决策须由主治医师最终确认。', 'This report is automatically generated by Firefly Isle Clinical AI from original scans and pathology reports. Structured data has passed three review stages. All clinical decisions must be confirmed by the attending physician.'),
      exportPdf: text('导出 PDF', 'Export PDF'),
      editData: text('修正数据', 'Edit Data'),
      copyright: text('© 2024 临床智能档案。保留所有权利。', '© 2024 Clinical Intelligence Archive. All rights reserved.'),
    },
  },
} as const

export function getCopy<T extends LocaleText>(value: T, locale: Locale) {
  return value[locale]
}
