/**
 * [INPUT]: 依赖 @/components/app-shell 的设计复刻壳层与占位图，依赖 @/lib/theme 的 useTheme。
 * [OUTPUT]: 对外提供 WorkspacePage 组件，对应 /app。
 * [POS]: routes 的临床工作区实现，按 docs/design 中的 dark/light 工作区页面复刻输入画布与结构化输出布局。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import {
  ArchiveSideNav,
  DarkTopBar,
  QR_PLACEHOLDER,
  SCAN_PLACEHOLDER,
} from '@/components/app-shell'
import { useTheme } from '@/lib/theme'

function DarkWorkspacePage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] font-['Inter'] text-[#FAFAFA]">
      <DarkTopBar />
      <ArchiveSideNav dark />

      <main className="ml-0 min-h-screen bg-[#131313] pt-16 md:ml-[15%]">
        <section className="border-b border-[#262626] bg-[#0A0A0A] p-8">
          <div className="mx-auto max-w-6xl space-y-6">
            <div className="flex flex-col gap-2">
              <label className="font-['JetBrains_Mono'] text-[10px] uppercase tracking-widest text-[#FF3D00]">
                PATIENT_HISTORY_INPUT
              </label>
              <textarea
                className="h-48 w-full resize-none border-0 border-b border-[#262626] bg-[#1A1A1A] p-4 text-[#FAFAFA] outline-none placeholder:text-[#353534] focus:border-[#FF3D00] focus:border-b-2"
                placeholder="请描述患者的病情及治疗历程..."
              />
            </div>

            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <div className="group flex cursor-pointer flex-col items-center justify-center border-2 border-dashed border-[#262626] bg-[#131313] py-10 transition-colors hover:border-[#FF3D00]">
                <span className="material-symbols-outlined mb-2 text-4xl text-[#353534] group-hover:text-[#FF3D00]">
                  upload_file
                </span>
                <span className="font-['JetBrains_Mono'] text-[11px] uppercase tracking-widest text-[#353534] group-hover:text-[#FAFAFA]">
                  点击或拖拽上传图片/PDF
                </span>
              </div>
              <div className="flex items-center justify-center">
                <button className="flex h-full min-h-[120px] w-full flex-col items-center justify-center gap-3 bg-[#FF3D00] text-[#0A0A0A] transition-colors hover:bg-[#FAFAFA]">
                  <span className="material-symbols-outlined text-4xl" style={{ fontVariationSettings: "'FILL' 1" }}>
                    mic
                  </span>
                  <span className="font-['Inter_Tight'] text-xl font-black uppercase tracking-tighter">语音录入</span>
                </button>
              </div>
            </div>
          </div>
        </section>

        <section className="flex-1 bg-[#131313] p-8">
          <div className="relative mx-auto max-w-6xl overflow-hidden bg-white p-10 text-[#0A0A0A] shadow-2xl">
            <div className="pointer-events-none absolute right-0 top-0 select-none text-8xl font-black opacity-5 -rotate-12">
              FORENSIC
            </div>
            <div className="mb-8 flex items-end justify-between border-b-4 border-[#0A0A0A] pb-4">
              <div>
                <h1 className="font-['Inter_Tight'] text-5xl font-black leading-none tracking-tighter">
                  临床结构化报告
                </h1>
                <p className="mt-2 font-['JetBrains_Mono'] text-[10px] tracking-widest">
                  GENERATED BY ONE-PAGE FIREFLY AI ARCHIVE
                </p>
              </div>
              <div className="text-right">
                <p className="font-['JetBrains_Mono'] text-xs font-bold">REPORT_ID: 2024-X0892</p>
                <p className="font-['JetBrains_Mono'] text-xs">DATE: 2024.05.20</p>
              </div>
            </div>

            <div className="mb-8 grid grid-cols-4 border-2 border-[#0A0A0A]">
              {[
                ['AGE / 年龄', '54'],
                ['BLOOD TYPE / 血型', 'A+'],
                ['GENDER / 性别', '女'],
                ['WEIGHT / 体重', '62 KG'],
              ].map(([label, value], index) => (
                <div
                  key={label}
                  className={`bg-[#F0F0F0] p-2 ${index < 3 ? 'border-r border-[#0A0A0A]' : ''}`}
                >
                  <label className="block font-['JetBrains_Mono'] text-[9px] font-bold">{label}</label>
                  <span className="text-lg font-bold">{value}</span>
                </div>
              ))}
            </div>

            <div className="mb-8">
              <h2 className="mb-2 inline-block bg-[#0A0A0A] px-4 py-1 text-sm font-bold uppercase tracking-widest text-white">
                初发区块 / PRIMARY ONSET
              </h2>
              <table className="w-full border-2 border-[#0A0A0A] border-collapse">
                <tbody>
                  <tr className="border-b border-[#0A0A0A]">
                    <td className="w-1/4 border-r border-[#0A0A0A] bg-[#F0F0F0] p-2 font-bold">触发时间</td>
                    <td className="w-3/4 p-2">2022-03-15</td>
                  </tr>
                  <tr className="border-b border-[#0A0A0A]">
                    <td className="border-r border-[#0A0A0A] bg-[#F0F0F0] p-2 font-bold">初始方案</td>
                    <td className="p-2 font-medium">改良根治术 + AC-T 化疗方案</td>
                  </tr>
                  <tr className="border-b border-[#0A0A0A]">
                    <td className="border-r border-[#0A0A0A] bg-[#F0F0F0] p-2 font-bold">免疫组化 (IHC)</td>
                    <td className="p-2">
                      <div className="grid grid-cols-4 gap-4">
                        {[
                          ['ER', '80%(+)'],
                          ['PR', '20%(+)'],
                          ['HER2', '1(+)'],
                          ['Ki67', '15%'],
                        ].map(([label, value]) => (
                          <div key={label}>
                            <span className="block text-[10px] opacity-60">{label}</span>
                            <span className="font-bold">{value}</span>
                          </div>
                        ))}
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td className="border-r border-[#0A0A0A] bg-[#F0F0F0] p-2 font-bold">基因检测</td>
                    <td className="p-2 text-sm italic">BRCA1/2 突变：阴性 (Negative)</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div className="mb-8">
              <h2 className="mb-2 inline-block bg-[#0A0A0A] px-4 py-1 text-sm font-bold uppercase tracking-widest text-white">
                治疗线区块 / TREATMENT LINES
              </h2>
              {[
                {
                  title: '一线治疗 / FIRST LINE',
                  period: '2022.06 - 2023.01',
                  regimen: '他莫昔芬 (Tamoxifen) 20mg qd po',
                  biopsy: '左锁骨上淋巴结穿刺 (2022-05-30)',
                  ihc: 'ER(90%+), PR(10%+), HER2(0), Ki67(10%)',
                  gene: '未见明显驱动基因突变',
                  highlight: false,
                },
                {
                  title: '二线治疗 / SECOND LINE',
                  period: '2023.02 - 至今',
                  regimen: '氟维司群 + CDK4/6 抑制剂 (阿贝西利)',
                  biopsy: '肝脏占位穿刺活检 (2023-02-10)',
                  ihc: 'ER(70%+), PR(-), HER2(1+), Ki67(30%)',
                  gene: 'PIK3CA 突变阳性',
                  highlight: true,
                },
              ].map((line) => (
                <div className="mb-4 border-2 border-[#0A0A0A]" key={line.title}>
                  <div className="flex items-center justify-between bg-[#0A0A0A] p-2 text-white">
                    <span className="text-xs font-bold tracking-tighter">{line.title}</span>
                    <span className="font-['JetBrains_Mono'] text-[10px]">{line.period}</span>
                  </div>
                  <table className="w-full border-collapse">
                    <tbody>
                      {[
                        ['用药情况', line.regimen],
                        ['穿刺/活检', line.biopsy],
                        ['免疫组化', line.ihc],
                        ['基因检测', line.gene],
                      ].map(([label, value], index) => (
                        <tr className={index < 3 ? 'border-b border-[#0A0A0A]' : ''} key={label}>
                          <td className="w-1/4 border-r border-[#0A0A0A] bg-[#F0F0F0] p-2 text-xs font-bold">{label}</td>
                          <td className={`p-2 text-sm ${line.highlight && label === '基因检测' ? 'font-bold text-[#FF3D00]' : ''}`}>
                            {value}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ))}
            </div>

            <div className="mt-12 flex items-center justify-between border-t-2 border-[#0A0A0A] pt-4">
              <div className="max-w-[400px] font-['JetBrains_Mono'] text-[9px]">
                声明：本报告由人工智能辅助系统自动提取，仅供医疗专业人士参考。最终诊断需结合原始影像及病理报告。
              </div>
              <div className="flex flex-col items-center border border-[#0A0A0A] p-2">
                <div className="flex h-16 w-16 items-center justify-center bg-[#F0F0F0]">
                  <img alt="验证码" src={QR_PLACEHOLDER} />
                </div>
                <span className="mt-1 text-[8px]">扫码验证报告</span>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function LightWorkspacePage() {
  return (
    <div className="ff-light-workspace-bg min-h-screen text-[#111111]">
      <div className="flex min-h-screen">
        <ArchiveSideNav dark={false} />

        <main className="flex-1 overflow-y-auto bg-[#F9F9F7] p-12">
          <header className="mx-auto mb-12 w-full max-w-6xl">
            <div className="mb-4 flex items-end justify-between">
              <div>
                <h1 className="font-['Playfair_Display'] text-7xl font-black uppercase -tracking-widest text-[#111111]">
                  EXTRACTOR
                </h1>
                <p className="mt-2 font-['JetBrains_Mono'] text-xs uppercase tracking-widest opacity-60">
                  Session ID: AI-2949-01 // Clinical Intelligence Engine
                </p>
              </div>
              <div className="text-right font-['JetBrains_Mono'] text-xs opacity-40">
                <span className="block">DATE: 2024.05.20</span>
                <span className="block">LOCATION: SHANGHAI CLINIC</span>
              </div>
            </div>
            <div className="ff-light-double-rule" />
          </header>

          <section className="mx-auto grid w-full max-w-6xl grid-cols-12 gap-8">
            <div className="col-span-8 flex flex-col gap-6">
              <div className="border-2 border-[#111111] bg-white p-6">
                <div className="mb-4 flex items-center justify-between">
                  <label className="font-['Inter'] text-xs font-bold uppercase tracking-[0.2em] text-[#111111]">
                    文字输入 / TEXT INPUT
                  </label>
                  <span className="font-['JetBrains_Mono'] text-[10px] font-bold text-[#CC0000]">
                    READY TO ANALYZE
                  </span>
                </div>
                <textarea
                  className="h-48 w-full resize-none border-0 bg-transparent text-xl leading-relaxed outline-none placeholder:opacity-20"
                  placeholder="在此输入患者病史或临床表现描述..."
                />
              </div>

              <div className="grid grid-cols-2 gap-6">
                <div className="flex cursor-pointer flex-col items-center justify-center border-2 border-dashed border-[#111111] bg-[#e0e0db]/20 p-6 transition-colors hover:bg-[#e0e0db]/40">
                  <img alt="Upload placeholder" className="mb-2 h-20 w-20 object-cover" src={SCAN_PLACEHOLDER} />
                  <span className="font-['Inter'] text-xs font-bold uppercase tracking-widest">
                    图片及 PDF 输入
                  </span>
                  <span className="mt-1 font-['JetBrains_Mono'] text-[10px] opacity-50">
                    Drag & Drop Documents
                  </span>
                </div>
                <div className="ff-light-hard-shadow flex cursor-pointer flex-col items-center justify-center bg-[#CC0000] p-6 text-white transition-all hover:-translate-y-1">
                  <span className="material-symbols-outlined mb-2 text-4xl" style={{ fontVariationSettings: "'FILL' 1" }}>
                    mic
                  </span>
                  <span className="font-['Inter'] text-xs font-bold uppercase tracking-widest">语音录入</span>
                  <span className="mt-1 font-['JetBrains_Mono'] text-[10px] opacity-80">HOLD TO RECORD</span>
                </div>
              </div>
            </div>

            <div className="col-span-4 flex flex-col gap-8 border-l-2 border-[#111111] pl-8">
              <div>
                <h3 className="mb-4 border-b border-[#111111] pb-2 font-['Playfair_Display'] text-2xl font-bold">
                  Instructional
                </h3>
                <p className="ff-light-drop-cap text-sm italic leading-relaxed">
                  Please ensure all medical records are anonymized before processing. The AI engine will cross-reference current symptoms with historic records to generate a comprehensive structural report.
                </p>
              </div>
              <div className="bg-[#111111] p-6 text-[#F9F9F7]">
                <h4 className="mb-4 font-['Inter'] text-[10px] font-bold uppercase tracking-widest">
                  Current Parameters
                </h4>
                <ul className="space-y-2 font-['JetBrains_Mono'] text-[11px] opacity-80">
                  <li className="flex justify-between"><span>MODEL</span><span>CLINIC-V4</span></li>
                  <li className="flex justify-between"><span>SENSITIVITY</span><span>HIGH</span></li>
                  <li className="flex justify-between"><span>LANGUAGE</span><span>ZH-CN</span></li>
                </ul>
              </div>
            </div>
          </section>

          <section className="mx-auto mt-8 w-full max-w-6xl">
            <div className="mb-6 flex items-baseline gap-4">
              <h2 className="font-['Newsreader'] text-4xl font-bold tracking-tighter">临床结构化报告</h2>
              <div className="h-[2px] flex-1 bg-[#111111]" />
            </div>
            <div className="grid grid-cols-12 gap-0 border-2 border-[#111111] bg-white">
              <div className="col-span-3 border-r-2 border-[#111111] bg-[#f4f4f2] p-6">
                <h3 className="mb-6 flex items-center gap-2 font-['Inter'] text-xs font-black uppercase tracking-[0.2em]">
                  <span className="material-symbols-outlined text-sm">person_search</span>
                  患者元数据
                </h3>
                <div className="space-y-6">
                  {[
                    ['Age / 年龄', '45'],
                    ['Blood Type / 血型', 'AB+'],
                    ['Sex / 性别', '女'],
                  ].map(([label, value]) => (
                    <div key={label}>
                      <span className="block font-['JetBrains_Mono'] text-[10px] uppercase opacity-60">{label}</span>
                      <span className="font-['Newsreader'] text-3xl font-bold">{value}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="col-span-9 p-8 bg-white">
                <div className="mb-8 flex items-center justify-between">
                  <h3 className="font-['Inter'] text-xs font-black uppercase tracking-[0.2em]">
                    治疗时间轴 / TREATMENT TIMELINE
                  </h3>
                  <div className="flex gap-2">
                    <span className="h-2 w-2 bg-[#111111]" />
                    <span className="h-2 w-2 bg-[#111111]/20" />
                    <span className="h-2 w-2 bg-[#111111]/20" />
                  </div>
                </div>

                <div className="relative space-y-12 border-l-2 border-[#111111]/10 pl-12">
                  {[
                    {
                      date: '2024.04.12',
                      tag: 'Primary Symptom',
                      title: '初步诊断：持续性偏头痛',
                      desc: '患者主诉头痛伴有恶心，休息后无明显缓解。既往有轻度高血压病史。',
                      active: true,
                    },
                    {
                      date: '2024.04.28',
                      tag: 'Lab Result',
                      title: '生化检查与影像学分析',
                      desc: 'CT扫描未见明显占位，实验室检查显示炎性指标轻微升高。建议进行进一步睡眠监测。',
                      active: false,
                    },
                    {
                      date: '2024.05.15',
                      tag: 'Observation',
                      title: '随访与用药调整',
                      desc: '目前采用联合用药方案，患者反馈症状频率降低 40%。继续观察治疗方案的耐受性。',
                      active: false,
                    },
                  ].map((item, index) => (
                    <div className="relative" key={item.title}>
                      <span className={`absolute -left-[54px] top-0 h-3 w-3 ${index === 2 ? 'border-2 border-[#111111] bg-[#F9F9F7]' : 'bg-[#111111]'} ${item.active ? '' : 'opacity-40'}`} />
                      <div className="flex items-start justify-between">
                        <span className={`px-2 py-1 font-['JetBrains_Mono'] text-xs font-bold ${item.active ? 'bg-[#111111] text-[#F9F9F7]' : 'border border-[#111111]'}`}>
                          {item.date}
                        </span>
                        <span className={`font-['Inter'] text-[10px] font-bold uppercase ${item.active ? 'text-[#CC0000]' : 'text-[#111111]/40'}`}>
                          {item.tag}
                        </span>
                      </div>
                      <h4 className="mt-2 font-['Newsreader'] text-xl font-bold">{item.title}</h4>
                      <p className="mt-1 text-sm text-[#111111]/70">{item.desc}</p>
                    </div>
                  ))}
                </div>

                <div className="mt-12 grid grid-cols-2 gap-12 border-t border-[#111111]/10 pt-8">
                  <div>
                    <h5 className="mb-4 font-['Inter'] text-[10px] font-bold uppercase tracking-widest">Clinical Notes</h5>
                    <p className="text-xs italic opacity-60">
                      "The digital extraction of these patterns suggests a correlation between environmental stressors and acute episodes..."
                    </p>
                  </div>
                  <div className="flex flex-col justify-end">
                    <div className="flex items-center justify-between bg-[#eeeeec] p-4">
                      <div className="flex items-center gap-3">
                        <div className="flex h-10 w-10 items-center justify-center bg-[#111111] font-['Playfair_Display'] text-xl font-black text-[#F9F9F7]">
                          AI
                        </div>
                        <div>
                          <p className="font-['Inter'] text-[10px] font-bold uppercase leading-none">
                            Verified by AI Agent
                          </p>
                          <p className="font-['JetBrains_Mono'] text-[9px] opacity-60">CONFIDENCE: 98.4%</p>
                        </div>
                      </div>
                      <span className="material-symbols-outlined text-[#CC0000]">verified</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <footer className="mx-auto mt-12 w-full max-w-6xl border-t border-[#111111]/10 py-12 text-center opacity-30">
            <span className="font-['Playfair_Display'] text-4xl font-black uppercase italic tracking-tighter">
              Ink &amp; Archive
            </span>
            <p className="mt-2 font-['JetBrains_Mono'] text-[10px] uppercase tracking-[0.4em]">
              Protocol: CLINICAL-ALPHA-01 // NO UNMATCHED DATA
            </p>
          </footer>
        </main>
      </div>
    </div>
  )
}

export function WorkspacePage() {
  const { theme } = useTheme()

  return theme === 'dark' ? <DarkWorkspacePage /> : <LightWorkspacePage />
}
