/**
 * [INPUT]: 依赖 @/components/system/surfaces 的 ActionSurface 与 PanelSurface，依赖 @/components/timeline/TimelineTable 的正式表格渲染器，依赖 @/components/app-shell 的 QR 占位图与外部传入的导出/保存状态。
 * [OUTPUT]: 对外提供 ReportPreviewFrame 组件，统一 dark/light 报告预览框架与 TimelineTable 包裹结构。
 * [POS]: components/workspace 的报告预览区块，被 workspace-page 组合，用于把预览 scaffold 从 route 中收口到 feature 层。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import { QR_PLACEHOLDER } from '@/components/app-shell'
import { ActionSurface, PanelSurface } from '@/components/system/surfaces'
import { TimelineTable } from '@/components/timeline/TimelineTable'
import type { PatientFieldTarget, PatientRecord } from '@/types/patient'

type ReportPreviewFrameProps = {
  followUpCount?: number
  isExtracting: boolean
  isSaving: boolean
  onCommitField: (target: PatientFieldTarget, value: string) => void
  record: PatientRecord
  remainingMissing: string[]
  setReportRef: (node: HTMLDivElement | null) => void
  theme: 'dark' | 'light'
}

export function ReportPreviewFrame({
  followUpCount = 0,
  isExtracting,
  isSaving,
  onCommitField,
  record,
  remainingMissing,
  setReportRef,
  theme,
}: ReportPreviewFrameProps) {
  if (theme === 'dark') {
    return (
      <div
        ref={setReportRef}
        className="relative overflow-hidden border border-[var(--ff-border-muted)] bg-[var(--ff-surface-panel)] p-10 text-[var(--ff-text-primary)] shadow-lg"
      >
        <div className="mb-8 flex items-end justify-between border-b-4 border-[var(--ff-border-default)] pb-4">
          <div>
            <h1 className="font-['Inter_Tight'] text-5xl font-black leading-none tracking-tighter">临床结构化报告</h1>
            <p className="mt-2 font-['JetBrains_Mono'] text-[10px] tracking-widest text-[var(--ff-text-secondary)]">
              GENERATED BY ONE-PAGE FIREFLY AI ARCHIVE
            </p>
          </div>
          <div className="text-right text-[var(--ff-text-secondary)]">
            <p className="font-['JetBrains_Mono'] text-xs font-bold text-[var(--ff-text-primary)]">REPORT_ID: LIVE-DRAFT</p>
            <p className="font-['JetBrains_Mono'] text-xs">MISSING: {remainingMissing.length}</p>
          </div>
        </div>

        <TimelineTable disabled={isExtracting || isSaving} onCommitField={onCommitField} record={record} theme="dark" />

        <div className="mt-12 flex items-center justify-between border-t-2 border-[var(--ff-border-default)] pt-4">
          <div className="max-w-[400px] font-['JetBrains_Mono'] text-[9px] text-[var(--ff-text-secondary)]">
            声明：本报告由人工智能辅助系统自动提取，仅供医疗专业人士参考。最终诊断需结合原始影像及病理报告。
          </div>
          <div className="flex flex-col items-center border border-[var(--ff-border-default)] p-2">
            <div className="flex h-16 w-16 items-center justify-center bg-[var(--ff-surface-soft)]">
              <img alt="验证码" src={QR_PLACEHOLDER} />
            </div>
            <span className="mt-1 text-[8px] text-[var(--ff-text-secondary)]">扫码验证报告</span>
          </div>
        </div>
      </div>
    )
  }

  return (
    <PanelSurface className="p-8" theme="light" tone="panel">
      <div ref={setReportRef}>
        <TimelineTable disabled={isExtracting || isSaving} onCommitField={onCommitField} record={record} theme="light" />

        <div className="mt-12 grid grid-cols-2 gap-12 border-t border-[var(--ff-border-muted)] pt-8">
          <div>
            <h5 className="mb-4 font-['Inter'] text-[10px] font-bold uppercase tracking-widest">Clinical Notes</h5>
            <p className="text-xs italic text-[var(--ff-text-secondary)]">
              {remainingMissing.length > 0
                ? `仍待补充：${remainingMissing.join('、')}`
                : '关键临床字段已补齐，可进入下一阶段渲染。'}
            </p>
          </div>
          <div className="flex flex-col justify-end">
            <ActionSurface className="flex items-center justify-between p-4" theme="light" tone="soft">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center bg-[var(--ff-text-primary)] font-['Playfair_Display'] text-xl font-black text-[var(--ff-surface-base)]">
                  AI
                </div>
                <div>
                  <p className="font-['Inter'] text-[10px] font-bold uppercase leading-none">Verified by AI Agent</p>
                  <p className="font-['JetBrains_Mono'] text-[9px] text-[var(--ff-text-secondary)]">
                    FOLLOW-UPS USED: {followUpCount}
                  </p>
                </div>
              </div>
              <span className="material-symbols-outlined text-[var(--ff-accent-warning)]">verified</span>
            </ActionSurface>
          </div>
        </div>
      </div>
    </PanelSurface>
  )
}
